---
#
- name: Gather only registered virtual machines
  vmware_vm_info:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    vm_type: vm
    validate_certs: 'no'
  delegate_to: localhost
  register: vm_info

#
- name: Set fact of virtual machine's name of DSM Agent
  set_fact:
    dsm_agent_vm_name: "{{ ( vm_info.virtual_machines | select('search', dsm_agent_vmname ) ) }}"

    #  | list | string | split(' '))[1] | regex_replace('\"', '') | regex_replace(\"'\", '')  | regex_replace(',', '') }}"
    # dsm_agent_vm_name: "{{ ( vm_info.virtual_machines | select('search', dsm_agent_vmname ) | list | string | split(' '))[1] | regex_replace('\"', '') | regex_replace(\"'\", '')  | regex_replace(',', '') }}"

#
- debug:
    msg: "{{ dsm_agent_vm_name }}"

- meta: end_play

#
- name: Wait for the virtual machine to shutdown
  vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: 'no'
    name: "{{ dsm_agent_vm_name }}"
    state: shutdown-guest
    state_change_timeout: 200
  delegate_to: localhost
  register: vm_shutdown

#
- name: Set the state of a virtual machine to poweroff
  vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: 'no'
    # folder: "/{{ datacenter_name }}/vm/my_folder"
    name: "{{ dsm_agent_vm_name }}"
    state: powered-off
  delegate_to: localhost
  register: vm_poweroff

#
- name: Remove virtual machine - "{{ dsm_agent_vm_name }}"
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: 'no'
    cluster: ""
    name: "{{ dsm_agent_vm_name }}"
    state: absent
  delegate_to: localhost
  register: vm_removed
