---
- hosts: localhost
  gather_facts: true
  vars:
    deploy_ovf: false
    add_new_network_adapter: false
    configure_new_network: false
    uninstall_vcenter: false
    create_users: true
    create_roles: true
    delete_roles: true
    delete_users: true
  roles:
    - vcenter
#    - provider
#    - agent
#    - minio
