---
- hosts: localhost
  gather_facts: true
  vars:
    deploy_ovf: true
    add_new_network_adapter: true
    configure_new_network: true
    uninstall_vcenter: false
    create_users: false
    create_roles: false
  roles:
    - provider
    - agent
#    - vcenter
#    - minio
