---
- hosts: localhost
  gather_facts: true
  vars:
    deploy_ovf: true
    add_new_network_adapter: true
    configure_new_network: true
    uninstall_vcenter: false
    delete_roles: false
    delete_users: false
  roles:
    - agent
    - provider
#    - vcenter
#    - minio
