---
- hosts: localhost
  gather_facts: true
  vars:
    deploy_ovf: true
    add_new_network_adapter: true
    configure_new_network: true
  roles:
#    - agent
#    - provider
#    - minio
#    - vcenter
