esxi_address: '192.168.0.101'
root_username: 'root'
root_password: 'Changeme12!@'
vcenter_hostname: 'vcenter.jtest.pivotal.io'
vcenter_username: 'administrator@vsphere.local'
vcenter_address: '192.168.0.102'
vcenter_password: 'Changeme12!@'
datastore_name: 'datastore1'
datacenter_name: 'jDC01'
cluster_name: 'jClu01'
resourcepool_name: ''
# resourcepool_name: 'Discovered virtual machine'
net_prefix: '24'
net_gateway: '192.168.0.1'
dns_servers: '192.168.0.199,168.126.63.1'
domain: 'dms-provider.jtest.pivotal.io'
searchpath: 'jtest.pivotal.io'
dsm_provider_size: '50G'
folder_name: ''
dsm_provider_ova_file: 'roles/provider/files/dms-provider-va-1.5.0.2980-21842200.ova'
