- name: Add ESXi Host to vCenter
  community.vmware.vmware_host:
    hostname: '{{ vcenter.hostname }}'
    username: '{{ vcenter.username }}'
    password: '{{ vcenter.password }}'
    datacenter: '{{ vcenter.datacenter }}'
    cluster: '{{ vcenter.cluster }}'
    esxi_hostname: '{{ esxi.ipaddr }}'
    esxi_username: '{{ esxi.username }}'
    esxi_password: '{{ esxi.password }}'
    state: present
    validate_certs: false
  delegate_to: localhost
