- name: Create Cluster
  vmware_cluster:
    hostname: '{{ vcenter.hostname }}'
    username: '{{ vcenter.username }}'
    password: '{{ vcenter.password }}'
    datacenter_name: "{{ vcenter.datacenter }}"
    cluster_name: "{{ vcenter.cluster }}"
    validate_certs: false
  delegate_to: localhost
