- name: Create Cluster
  vmware_cluster:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter_name: "{{ datacenter_name }}"
    cluster_name: "{{ cluster_name }}"
    validate_certs: false
  delegate_to: localhost
