- name: Create Datacenter
  vmware_datacenter:
    hostname: '{{ vcenter.hostname }}'
    username: '{{ vcenter.username }}'
    password: '{{ vcenter.password }}'
    datacenter_name: '{{ vcenter.datacenter }}'
    state: present
    validate_certs: false
  delegate_to: localhost
