#
- name: Disassign user and role to Object
  community.vmware.vmware_object_role_permission:
    hostname: "{{ vcenter.hostname }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    role: "{{ item.role }}"
    principal: "vsphere.local\\{{ item.user_name }}"
    object_type: "{{ item.obj_type }}"
    object_name: "{{ item.obj_name }}"
    state: absent
    validate_certs: false
  ignore_errors: true
  with_items: "{{ assign_objects_list }}"
  delegate_to: localhost

#- name: Disassign dsm-user to Administrator
#  community.vmware.vmware_object_role_permission:
#    hostname: '{{ vcenter.hostname }}'
#    username: '{{ vcenter.username }}'
#    password: '{{ vcenter.password }}'
#    role: Admin
#    principal: "vsphere.local\\dsm-user"
#    object_name: ""
#    state: absent
#    validate_certs: false
#  ignore_errors: true
#  delegate_to: localhost

#
- name: Remove local role with privileges to vCenter
  vmware_local_role_manager:
    hostname: "{{ vcenter.hostname }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    local_role_name: "{{ item.name }}"
    local_privilege_ids: "{{ item.role }}"
    state: absent
    force_remove: true
    validate_certs: false
  ignore_errors: true
  with_items: "{{ add_roles_list }}"
  delegate_to: localhost
