- name: Remove local role with privileges to vCenter
  vmware_local_role_manager:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    local_role_name: "{{ item.name }}"
    local_privilege_ids: "{{ item.role }}"
    state: absent
    validate_certs: false
  with_items: "{{ add_roles_list }}"
  delegate_to: localhost

- name: Disassign user and role to Object
  community.vmware.vmware_object_role_permission:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    role: '{{ item.role }}'
    principal: '{{ item.user_name }}'
    object_type: '{{ item.obj_type }}'
    object_name: '{{ item.obj_name }}'
    state: absent
    validate_certs: false
  with_items: "{{ assign_objects_list }}"
  delegate_to: localhost
