---
#
- name: Gather only registered virtual machines
  vmware_vm_info:
    hostname: '{{ esxi_address }}'
    username: '{{ esxi_username }}'
    password: '{{ esxi_password }}'
    vm_type: vm
    validate_certs: 'no'
  delegate_to: localhost
  register: vm_info

#
- name: Set fact for virtual machine's name of vCenter
  set_fact:
    vcenter_vm_name: "{{ ( vm_info.virtual_machines | select('search', 'vcenter') | list | string | split(' '))[1] | regex_replace('\"', '') | regex_replace(\"'\", '')  | regex_replace(',', '') }}"

#
- debug:
    msg: "{{ vcenter_vm_name }}"

#
- name: Wait for the vCenter Virtual Machine to shutdown
  vmware_guest_powerstate:
    hostname: "{{ esxi_address }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
    name: "{{ vcenter_vm_name }}"
    validate_certs: 'no'
    state: shutdown-guest
    state_change_timeout: 200
  delegate_to: localhost
  register: vm_shutdown

#
- name: Set the state of vCenter Virtual Machine to poweroff
  vmware_guest_powerstate:
    hostname: "{{ esxi_address }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
    validate_certs: 'no'
    # folder: "/{{ datacenter_name }}/vm/my_folder"
    name: "{{ vcenter_vm_name }}"
    state: powered-off
  delegate_to: localhost
  register: vm_poweroff

#- meta: end_play

- name: Remove virtual machine - "{{ vcenter_vm_name }}"
  vmware_guest:
    hostname: "{{ esxi_address }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
    validate_certs: no
    cluster: ""
    name: "{{ vcenter_vm_name }}"
    state: absent
  delegate_to: localhost
  register: vm_removed
